### ISSUE TITLE
Please consider relicensing under Apache 2.0 license

### ISSUE THREAD

**Issue by obscurerichard** [tomekkup/spring-addons#1]
The Spring framework itself is licensed under the Apache 2.0 license. However, your RedisSessionRegistry.java source file indicates that it is licensed under the GNU GPL v.2 license. 

Would you consider relicensing this software under the same terms that Spring is licensed under, the [Apache 2.0 license](http://www.apache.org/licenses/LICENSE-2.0.html)? This would permit people to distribute and use this under the same terms that the Spring framework itself is used.

**Comment by obscurerichard** [comment]
Pretty please consider relicensing, or close the issue?

**Comment by tomekkup** [comment]
I'm closing due to a lack of time
